### PR TITLE
Migration

### PR DESCRIPTION
**Pull request by hidamaru**
The migration to unity 5.* from the old switch-project is now complete.

### CODE REVIEW

**Comment by hidamaru** [comment]
I have no idea why there are conflicts, nothing has changed in master what I know.

**Comment by langest** [comment]
Now it is mergable.
Was a conflict in git ignore and some files that had been removed in master. Fixed It for you. ;)

**Comment by hidamaru** [comment]
Yes, and now 6 scenes are missing and I'm pretty sure there are scripts that are not updated. I managed to do this too but then the master looked nothing like the migration branch did. This change has to be reverted and we need to find the problem, because right now the only correct copy of the work I did is on my computer.

**Comment by hidamaru** [comment]
In this commit: https://github.com/EzGaming/Switch2/commit/8686b77bc7dd49b47a5ded455017f4ce7028028d

Files like Assets/Scenes/BuildingSite.unity and Assets/Scenes/City.unity are no longe in the masterbranch. They were present in the migration-branch when the pull request was created.

In this commit: https://github.com/EzGaming/Switch2/commit/ed7606ba5005697a8893441ad445b2a6802707cc

Many subfolders for the scripts where created like "Abstract", "CharacterControllers" etc. where created The only subfolder remaining is the "CharacterControllers"-subfolder and that folder is missing scripts.

**Pull request merged**
